### ISSUE TITLE
wrong pool

### ISSUE THREAD

**Issue by Retropex** [benjamin-wilson/public-pool-ui#5]
When executing the ui, it shows me the public pool statistics and not those of my own pool how to fix this?

**Comment by Retropex** [comment]
solved

For posterity, the following file must be modified for prod:

```
src/environments/environment.prod.ts
```

**Comment by warioishere** [comment]
> solved
> 
> For posterity, the following file must be modified for prod:
> 
> ```
> src/environments/environment.prod.ts
> ```

changed the file, nothing changes restarted the docker container, do I need to rebuild?

**Comment by Retropex** [comment]
This was working for standalone installation
